version: 1.0.2-CI-{build}
image: Visual Studio 2019 Preview
configuration: Release
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
before_build:
  - ps: dotnet clean
  - ps: nuget restore Askmethat.Aspnet.JsonLocalizer.sln
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "$env:version"
      }
build:
  project: Askmethat.Aspnet.JsonLocalizer.sln
  verbosity: minimal
after_build:
  - ps: >-
      dotnet pack .\Askmethat.Aspnet.JsonLocalizer\Askmethat.Aspnet.JsonLocalizer.csproj -o .\ -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nuget_key:
    secure: GYX+JFKT7xo9zxtb5hhpSp7bmqTpljtH8hNfWMAOjZPHaofZ4RffdjFqZJRr8pxW
deploy:
  - provider: NuGet
    api_key:
      secure: GYX+JFKT7xo9zxtb5hhpSp7bmqTpljtH8hNfWMAOjZPHaofZ4RffdjFqZJRr8pxW
    on:
      appveyor_repo_tag: true
